version: '2'
services:
    deepstream:
        #build: "."
        image: deepstreamio/deepstream.io
        ports:
            - "6020:6020"
            - "6021:6021"
        volumes:
            - ./conf:/usr/local/deepstream/conf
            - ./var:/usr/local/deepstream/var
        depends_on:
            - redis
            - rethinkdb
