version: '2'
services:
    deepstream:
        build: "."
        ports:
            - "6020:6020"
            - "6021:6021"
        volumes:
            - ./conf:/usr/local/deepstream/conf
            - ./var:/usr/local/deepstream/var
        depends_on:
            - redis
            - rethinkdb
    deepstream-search-provider:
        # build: "../deepstream.io-provider-search-rethinkdb/1.1.1"
        image: deepstreamio/deepstream.io-provider-search-rethinkdb
        environment:
            - DEEPSTREAM_HOST=deepstream
            - DEEPSTREAM_PORT=6021
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
            - "8080:8080"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data
